apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ticketing-app-microservice
build:
  artifacts:
    - image: navidkamal/auth
      context: ticketing/auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ticketing/infra/k8s/auth-depl.yaml
